### PR TITLE
make compatible with new estateguru portal

### LINKED ISSUE #8: EstateGuru changed Website
EstateGuru changed Website, so the extension stopped working

### PR DESCRIPTION
**Pull request by henry-spanka**
Estateguru has a new Portal which also enforces 2FA Authentication (SMS).

I have implemented 2FA authentication and cleaned up the code a bit.

Closes #8

### CODE REVIEW

**Comment by beanieboi** [comment]
Thank you! I closed my estatguru account a while ago and I can test this. I will merge it as is.

**Comment by nicoherpich** [comment]
> Thank you! I closed my estatguru account a while ago and I can test this. I will merge it as is.

Hi beanieboi, thank you for your quick response! The changed works, but not completly :-/ I get the data from the website, but it seams to have a format issue:

My account has around 15.123,45€, in moneymoney i get a statement with 15,12€ -> i think it is an ". and ," issue for seperating the thousands.

**Comment by henry-spanka** [comment]
@nicoherpich I assume your balance is displayed with the decimal separator "," and thousand separator ".", correct? My default Estateguru portal language is English and the extension should always request the English version of the portal but there might be some issue. I will check if we can somehow force a specific number format. Otherwise we might parse the number format differently depending on the account language.

**Comment by nicoherpich** [comment]
> @nicoherpich I assume your balance is displayed with the decimal separator "," and thousand separator ".", correct? My default Estateguru portal language is English and the extension should always request the English version of the portal but there might be some issue. I will check if we can somehow force a specific number format. Otherwise we might parse the number format differently depending on the account language.

at the moment it is shown €15,891.14

my portal is in english but my account is a german one. is there anywhere a setting to define it in english? possibly it is a automatic thing based on the browser language or OS-setting?

**Comment by henry-spanka** [comment]
@nicoherpich Have you updated your plugin after my commit 2 days ago? It should override the OS setting.

**Comment by nicoherpich** [comment]
> @nicoherpich Have you updated your plugin after my commit 2 days ago? It should override the OS setting.

i used the [ff6f9b1](https://github.com/beanieboi/moneymoney-estateguru/commit/ff6f9b1b2c15e948bde0c8be6a93a999215c70dc) commit, the parsing problem still exists

**Comment by henry-spanka** [comment]
> > @nicoherpich Have you updated your plugin after my commit 2 days ago? It should override the OS setting.
> 
> i used the [ff6f9b1](https://github.com/beanieboi/moneymoney-estateguru/commit/ff6f9b1b2c15e948bde0c8be6a93a999215c70dc) commit, the parsing problem still exists

What is your OS language?

Please try to add the following line after line 129:
```lua
connection.language = "en-gb"
```

**Comment by nicoherpich** [comment]
> > > @nicoherpich Have you updated your plugin after my commit 2 days ago? It should override the OS setting.
> > 
> > 
> > i used the [ff6f9b1](https://github.com/beanieboi/moneymoney-estateguru/commit/ff6f9b1b2c15e948bde0c8be6a93a999215c70dc) commit, the parsing problem still exists
> 
> What is your OS language?
> 
> Please try to add the following line after line 129:
> 
> ```lua
> connection.language = "en-gb"
> ```

OS language is german

your change fixed the issue! works pretty well, thank you so much!

**Pull request merged**
